### ISSUE TITLE
Any way to run this without docker?

### ISSUE THREAD

**Issue by Yankees4life** [mgoodings/patbrid#6]
Hello

Is there any way to run this without docker? I find the performance with docker to be lacking.

**Comment by mgoodings** [comment]
Hey @Yankees4life, you can install NodeJS (12+), download the project, set the environment variables from the README and use `$ node index.js` in the project root folder.

Not sure what performance issues you are having though as this simply calls remote API's and doesn't do any actual downloading. It's very low throughput for requests. Try clearing your Real-Debrid torrent list and removing any old torrents from the watch directory just to be safe.

**Comment by Yankees4life** [comment]
Tried that and that didn't work. It keeps throwing up EBUSY errors (I guess that has something to do with chokidar)
